---

- name: "[Debian] - install tzdata package for timezone"
  apt:
    name: tzdata
  when: ansible_os_family == "Debian"

- name: "[Debian] - Set timezone"
  copy:
    content: '{{ timezone }}\n'
    dest: /etc/timezone
    mode: 0444
  when: ansible_os_family == "Debian"
