---

- name: Use role specyfic for current OS
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yaml"
    - "{{ ansible_distribution }}.yaml"
    - "{{ ansible_os_family|lower }}.yaml"
  tags:
    - utils

- name: Screen configuration
  template:
    src: "etc/screenrc"
    dest: "/etc/screenrc"
    owner: root
    group: root
    mode: "0644"
  tags:
    - utils
    - screen

- name: Ensure /etc/vim exist
  file:
    path: "/etc/vim"
    state: directory
  tags:
    - utils
    - vim

- name: Vim configuration
  template:
    src: "etc/vim/vimrc.local"
    dest: "/etc/vim/vimrc.local"
    owner: root
    group: root
    mode: "0644"
  tags:
    - utils
    - vim